# Generated by Django 2.1.5 on 2020-03-08 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snack')], default=1, max_length=7)),
                ('servings', models.IntegerField(default=1)),
                ('ingredients', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('calorie_unit', models.CharField(default='kcal', max_length=12)),
                ('calorie_quantity', models.FloatField(default=0.0)),
                ('fat_unit', models.CharField(default='g', max_length=12)),
                ('fat_quantity', models.FloatField(default=0.0)),
                ('protein_unit', models.CharField(default='g', max_length=12)),
                ('protein_quantity', models.FloatField(default=0.0)),
                ('carbs_unit', models.CharField(default='g', max_length=12)),
                ('carbs_quantity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macro_mate.UserProfile'),
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
