# Generated by Django 2.1.5 on 2020-03-09 17:20

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('macro_mate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner'), ('SN', 'Snack')], max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='categories',
        ),
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(to='macro_mate.MealCategory'),
        ),
    ]
