# Generated by Django 2.1.5 on 2020-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_mate', '0002_auto_20200309_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcategory',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNC', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=12, unique=True),
        ),
    ]
