# Generated by Django 2.1.5 on 2020-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_mate', '0004_auto_20200309_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcategory',
            name='category',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
