# Generated by Django 2.1.5 on 2020-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_mate', '0005_auto_20200309_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='calorie_quantity',
            new_name='calories_quantity',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='calorie_unit',
            new_name='calories_unit',
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
